
language: python
python:
  - 3.6
  - 3.7
  - 3.8

before_install:
  - sudo apt-get update
  - sudo apt-get -y install gfortran 
  - sudo apt-get -y install binutils
  - sudo apt-get -y install git
  - python --version
  - pip install -U pip
  - pip install -U pytest

install:
  - pip install -r requirements.txt # install package
  - pip install .

script: pytest # run tests
